//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpEncrypt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpEncrypt.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:.
        /// </summary>
        internal static string _0colon {
            get {
                return ResourceManager.GetString("0colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string _0colon1 {
            get {
                return ResourceManager.GetString("0colon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string _0Interpolation {
            get {
                return ResourceManager.GetString("0Interpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} selected.
        /// </summary>
        internal static string _0OutOfNSelected {
            get {
                return ResourceManager.GetString("0OutOfNSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("AboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error has occurred..
        /// </summary>
        internal static string ACriticalErrorHasOccurred {
            get {
                return ResourceManager.GetString("ACriticalErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Tasks.
        /// </summary>
        internal static string ActiveTasks {
            get {
                return ResourceManager.GetString("ActiveTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Tasks Warning.
        /// </summary>
        internal static string ActiveTasksWarning {
            get {
                return ResourceManager.GetString("ActiveTasksWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} tasks..
        /// </summary>
        internal static string AddedNTasks {
            get {
                return ResourceManager.GetString("AddedNTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a file to be secured..
        /// </summary>
        internal static string AddSecuredFile {
            get {
                return ResourceManager.GetString("AddSecuredFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Secured File.
        /// </summary>
        internal static string AddSecuredFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("AddSecuredFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Secured Folder.
        /// </summary>
        internal static string AddSecuredFolderToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("AddSecuredFolderToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        internal static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A task of the same type has been detected..
        /// </summary>
        internal static string ADuplicateTaskHasBeenDetected {
            get {
                return ResourceManager.GetString("ADuplicateTaskHasBeenDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string AdvancedMenuStrip {
            get {
                return ResourceManager.GetString("AdvancedMenuStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string AdvancedToolStripMenuItem {
            get {
                return ResourceManager.GetString("AdvancedToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES Password-Based.
        /// </summary>
        internal static string AESPasswordBasedToolStripMenuItem {
            get {
                return ResourceManager.GetString("AESPasswordBasedToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AESPasswordStore.aesstore.
        /// </summary>
        internal static string AESPasswordStoreFile {
            get {
                return ResourceManager.GetString("AESPasswordStoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A key must be created to use this store, this key should be stored on removable media and kept a safe place. If a key is copied from a hard drive to a removable disk, the hard drive&apos;s free space should be wiped..
        /// </summary>
        internal static string AKeyMustBeSavedForThisOTPStore {
            get {
                return ResourceManager.GetString("AKeyMustBeSavedForThisOTPStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        internal static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has occurred: {0}.
        /// </summary>
        internal static string AnExceptionHasOccurred {
            get {
                return ResourceManager.GetString("AnExceptionHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymize File Name.
        /// </summary>
        internal static string AnonymizeFileNameToolStripMenuItem {
            get {
                return ResourceManager.GetString("AnonymizeFileNameToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymize File Name.
        /// </summary>
        internal static string AnonymousRenameToolStripMenuItem {
            get {
                return ResourceManager.GetString("AnonymousRenameToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure_ {
            get {
                return ResourceManager.GetString("AreYouSure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Space (GB).
        /// </summary>
        internal static string AvailableSize {
            get {
                return ResourceManager.GetString("AvailableSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Anonymize File Names.
        /// </summary>
        internal static string BulkAnonymousRenameToolStripMenuItem {
            get {
                return ResourceManager.GetString("BulkAnonymousRenameToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Deanonymize File Names.
        /// </summary>
        internal static string BulkDeanonymizeFileNamesToolStripMenuItem {
            get {
                return ResourceManager.GetString("BulkDeanonymizeFileNamesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All Future Tasks.
        /// </summary>
        internal static string CancelAllFutureTasksToolStripMenuItem {
            get {
                return ResourceManager.GetString("CancelAllFutureTasksToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Session Password.
        /// </summary>
        internal static string ChangeSessionPasswordToolStripMenuItem {
            get {
                return ResourceManager.GetString("ChangeSessionPasswordToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Secured Files Grid.
        /// </summary>
        internal static string ClearSecuredFilesListToolStripMenuItem {
            get {
                return ResourceManager.GetString("ClearSecuredFilesListToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Secured Folders Grid.
        /// </summary>
        internal static string ClearSecuredFoldersGridToolStripMenuItem {
            get {
                return ResourceManager.GetString("ClearSecuredFoldersGridToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Session Password.
        /// </summary>
        internal static string ClearSessionPassword {
            get {
                return ResourceManager.GetString("ClearSessionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Tasks.
        /// </summary>
        internal static string ClearTasks {
            get {
                return ResourceManager.GetString("ClearTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select encrypted files to share keys with others..
        /// </summary>
        internal static string ClickToShare {
            get {
                return ResourceManager.GetString("ClickToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Tasks.
        /// </summary>
        internal static string CompletedTasks {
            get {
                return ResourceManager.GetString("CompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Oliver Bathurst 2020.
        /// </summary>
        internal static string CreatedByCredits {
            get {
                return ResourceManager.GetString("CreatedByCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        internal static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Value.
        /// </summary>
        internal static string CurrentValue {
            get {
                return ResourceManager.GetString("CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deanonymize File Name.
        /// </summary>
        internal static string DeanonymiseFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("DeanonymiseFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deanonymize File Name.
        /// </summary>
        internal static string DeanonymizeFileNameToolStripMenuItem {
            get {
                return ResourceManager.GetString("DeanonymizeFileNameToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Enabled.
        /// </summary>
        internal static string DebugEnabled {
            get {
                return ResourceManager.GetString("DebugEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string DebugMenuStrip {
            get {
                return ResourceManager.GetString("DebugMenuStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string DebugToolStripMenuItem {
            get {
                return ResourceManager.GetString("DebugToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt File.
        /// </summary>
        internal static string DecryptFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("DecryptFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt Permanently.
        /// </summary>
        internal static string DecryptPermanentlyToolStripMenuItem {
            get {
                return ResourceManager.GetString("DecryptPermanentlyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt Temporarily.
        /// </summary>
        internal static string DecryptTemporarilyToolStripMenuItem {
            get {
                return ResourceManager.GetString("DecryptTemporarilyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Grid Exclusion Lists.
        /// </summary>
        internal static string DeleteGridExclusionLists {
            get {
                return ResourceManager.GetString("DeleteGridExclusionLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog.
        /// </summary>
        internal static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Tools.
        /// </summary>
        internal static string DiskToolsToolStripMenuItem {
            get {
                return ResourceManager.GetString("DiskToolsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        internal static string DoesNotExist {
            get {
                return ResourceManager.GetString("DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Prompt For Password On Startup.
        /// </summary>
        internal static string DoNotPromptForPasswordOnStartup {
            get {
                return ResourceManager.GetString("DoNotPromptForPasswordOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        internal static string Drive {
            get {
                return ResourceManager.GetString("Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Format.
        /// </summary>
        internal static string DriveFormat {
            get {
                return ResourceManager.GetString("DriveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Type.
        /// </summary>
        internal static string DriveType {
            get {
                return ResourceManager.GetString("DriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate identity found, please use another..
        /// </summary>
        internal static string DuplicateIdentity {
            get {
                return ResourceManager.GetString("DuplicateIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .seef.
        /// </summary>
        internal static string EncryptedFileExtension {
            get {
                return ResourceManager.GetString("EncryptedFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt Encrypted File (*.seef)|*.seef.
        /// </summary>
        internal static string EncryptedFileFilter {
            get {
                return ResourceManager.GetString("EncryptedFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter timeout (ms):.
        /// </summary>
        internal static string EnterTimeout {
            get {
                return ResourceManager.GetString("EnterTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileExclusions.BIN.
        /// </summary>
        internal static string ExcludedFilesFile {
            get {
                return ResourceManager.GetString("ExcludedFilesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderExclusions.BIN.
        /// </summary>
        internal static string ExcludedFoldersFile {
            get {
                return ResourceManager.GetString("ExcludedFoldersFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitToolStripMenuItem {
            get {
                return ResourceManager.GetString("ExitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("ExitToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; cannot be empty..
        /// </summary>
        internal static string FieldCannotBeEmpty {
            get {
                return ResourceManager.GetString("FieldCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt Permanently.
        /// </summary>
        internal static string FileDecryptPermanently {
            get {
                return ResourceManager.GetString("FileDecryptPermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt Temporarily.
        /// </summary>
        internal static string FileDecryptTemporarily {
            get {
                return ResourceManager.GetString("FileDecryptTemporarily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenuStripItem {
            get {
                return ResourceManager.GetString("FileMenuStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Use.
        /// </summary>
        internal static string FirstUseDialogTitle {
            get {
                return ResourceManager.GetString("FirstUseDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Exit Disclaimer Hide.
        /// </summary>
        internal static string ForceExitDisclaimerHide {
            get {
                return ResourceManager.GetString("ForceExitDisclaimerHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Exit.
        /// </summary>
        internal static string ForceExitToolStripMenuItem {
            get {
                return ResourceManager.GetString("ForceExitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Key For File.
        /// </summary>
        internal static string GenerateKeyForFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("GenerateKeyForFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate New Key Pair.
        /// </summary>
        internal static string GenerateNewKeyPairToolStripMenuItem {
            get {
                return ResourceManager.GetString("GenerateNewKeyPairToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate New Password.
        /// </summary>
        internal static string GenerateNewPassword {
            get {
                return ResourceManager.GetString("GenerateNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        internal static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to password management..
        /// </summary>
        internal static string GoToPasswordManagement {
            get {
                return ResourceManager.GetString("GoToPasswordManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid View.
        /// </summary>
        internal static string GridView {
            get {
                return ResourceManager.GetString("GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Wipe Dialog.
        /// </summary>
        internal static string HDDWipeDialog {
            get {
                return ResourceManager.GetString("HDDWipeDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenuStrip {
            get {
                return ResourceManager.GetString("HelpMenuStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Excluded Secured Files.
        /// </summary>
        internal static string HideExcludedSecuredFilesToolStripMenuItem {
            get {
                return ResourceManager.GetString("HideExcludedSecuredFilesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Excluded Secured Folders.
        /// </summary>
        internal static string HideExcludedSecuredFoldersToolStripMenuItem {
            get {
                return ResourceManager.GetString("HideExcludedSecuredFoldersToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported Keys.
        /// </summary>
        internal static string ImportedKeysDir {
            get {
                return ResourceManager.GetString("ImportedKeysDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Public Key.
        /// </summary>
        internal static string ImportPublicKeyDialogTitle {
            get {
                return ResourceManager.GetString("ImportPublicKeyDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivity Timeout.
        /// </summary>
        internal static string InactivityTimeout {
            get {
                return ResourceManager.GetString("InactivityTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Subfolders.
        /// </summary>
        internal static string IncludeSubfolders {
            get {
                return ResourceManager.GetString("IncludeSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Settings Reset Dialog.
        /// </summary>
        internal static string IndividualSettingsResetDialog {
            get {
                return ResourceManager.GetString("IndividualSettingsResetDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Settings Reset.
        /// </summary>
        internal static string IndividualSettingsResetToolStripMenuItem {
            get {
                return ResourceManager.GetString("IndividualSettingsResetToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key, please generate a new key-pair..
        /// </summary>
        internal static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating a new key pair will overwrite any existing keys, your current session password will be used to encrypt your private key, continue?.
        /// </summary>
        internal static string KeyPairDisclaimer {
            get {
                return ResourceManager.GetString("KeyPairDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Code.
        /// </summary>
        internal static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Access.
        /// </summary>
        internal static string LastAccess {
            get {
                return ResourceManager.GetString("LastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        internal static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.txt.
        /// </summary>
        internal static string LogFileName {
            get {
                return ResourceManager.GetString("LogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string LoggingDir {
            get {
                return ResourceManager.GetString("LoggingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string LoggingToolStripMenuItem {
            get {
                return ResourceManager.GetString("LoggingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Management Store.
        /// </summary>
        internal static string ManagementStoreToolStripMenuItem {
            get {
                return ResourceManager.GetString("ManagementStoreToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Obfuscation Rounds.
        /// </summary>
        internal static string NameObfuscationRounds {
            get {
                return ResourceManager.GetString("NameObfuscationRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never show again.
        /// </summary>
        internal static string NeverShowAgain {
            get {
                return ResourceManager.GetString("NeverShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drives selected..
        /// </summary>
        internal static string NoDrivesSelected {
            get {
                return ResourceManager.GetString("NoDrivesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid container..
        /// </summary>
        internal static string NotAValidContainer {
            get {
                return ResourceManager.GetString("NotAValidContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Pad.
        /// </summary>
        internal static string OneTimePadToolStripMenuItem {
            get {
                return ResourceManager.GetString("OneTimePadToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Explorer Here.
        /// </summary>
        internal static string OpenExplorerHereToolStripMenuItem {
            get {
                return ResourceManager.GetString("OpenExplorerHereToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open a file from the default secure folder..
        /// </summary>
        internal static string OpenHomeFolder {
            get {
                return ResourceManager.GetString("OpenHomeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Password Manager.
        /// </summary>
        internal static string OpenPasswordManagerToolStripMenuItem {
            get {
                return ResourceManager.GetString("OpenPasswordManagerToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Secured.
        /// </summary>
        internal static string OpenSecuredToolStripMenuItem {
            get {
                return ResourceManager.GetString("OpenSecuredToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("OptionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The One Time Pad Vernam cipher requires that a key be generated that is either equal to or greater in length than that of the file to encrypt. e.g. a 2MB file will require at least a key of size 2MB. This cipher is widely regarded as perfect and unbreakable. It is therefore a necessity that the key is not stored with the encrypted file in a SharpEncrypt container, as the key would have to be encrypted with an inferior cipher. The next dialog will ask you for a location to store the key file. It is best to s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OTPDisclaimer {
            get {
                return ResourceManager.GetString("OTPDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Pad Disclaimer Hide.
        /// </summary>
        internal static string OtpDisclaimerHide {
            get {
                return ResourceManager.GetString("OtpDisclaimerHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Key-Based.
        /// </summary>
        internal static string OTPKeyBasedToolStripMenuItem {
            get {
                return ResourceManager.GetString("OTPKeyBasedToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPPasswordStore.seotppf.
        /// </summary>
        internal static string OTPPasswordStoreFile {
            get {
                return ResourceManager.GetString("OTPPasswordStoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Store Key File Path.
        /// </summary>
        internal static string OtpStoreKeyFilePath {
            get {
                return ResourceManager.GetString("OtpStoreKeyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Generator.
        /// </summary>
        internal static string PasswordGenerator {
            get {
                return ResourceManager.GetString("PasswordGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Input Dialog.
        /// </summary>
        internal static string PasswordInputDialogTitle {
            get {
                return ResourceManager.GetString("PasswordInputDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is invalid..
        /// </summary>
        internal static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided password is empty..
        /// </summary>
        internal static string PasswordIsEmpty {
            get {
                return ResourceManager.GetString("PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Management.
        /// </summary>
        internal static string PasswordManagementToolStripMenuItem {
            get {
                return ResourceManager.GetString("PasswordManagementToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Manager.
        /// </summary>
        internal static string PasswordManager {
            get {
                return ResourceManager.GetString("PasswordManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must not contain any restricted characters: {0}.
        /// </summary>
        internal static string PasswordRestrictedChars {
            get {
                return ResourceManager.GetString("PasswordRestrictedChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Startup Prompt Hide.
        /// </summary>
        internal static string PasswordStartupPromptHide {
            get {
                return ResourceManager.GetString("PasswordStartupPromptHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Stores.
        /// </summary>
        internal static string PasswordStoresDir {
            get {
                return ResourceManager.GetString("PasswordStoresDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key decryption password is incorrect..
        /// </summary>
        internal static string PrivateKeyDecryptionKeyIncorrect {
            get {
                return ResourceManager.GetString("PrivateKeyDecryptionKeyIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Obfuscation Rounds.
        /// </summary>
        internal static string PropertyObfuscationRounds {
            get {
                return ResourceManager.GetString("PropertyObfuscationRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided password is not valid for the selected file..
        /// </summary>
        internal static string ProvidedPasswordIsInvalid {
            get {
                return ResourceManager.GetString("ProvidedPasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will now be asked for your private key decryption password..
        /// </summary>
        internal static string ProvidePrivateKeyDecryptionKey {
            get {
                return ResourceManager.GetString("ProvidePrivateKeyDecryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicKeys.BIN.
        /// </summary>
        internal static string PubKeysFile {
            get {
                return ResourceManager.GetString("PubKeysFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A public key does not exist for this user, please generate another..
        /// </summary>
        internal static string PublicKeyDoesNotExist {
            get {
                return ResourceManager.GetString("PublicKeyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-encrypt On Lock.
        /// </summary>
        internal static string ReencryptOnLock {
            get {
                return ResourceManager.GetString("ReencryptOnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File From List But Keep Secured.
        /// </summary>
        internal static string RemoveFileFromListButKeepSecuredToolStripMenuItem {
            get {
                return ResourceManager.GetString("RemoveFileFromListButKeepSecuredToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Folder From List But Keep Secured.
        /// </summary>
        internal static string RemoveFolderFromListToolStripMenuItem {
            get {
                return ResourceManager.GetString("RemoveFolderFromListToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename To Original Name.
        /// </summary>
        internal static string RenameToOriginalToolStripMenuItem {
            get {
                return ResourceManager.GetString("RenameToOriginalToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename To Original Name.
        /// </summary>
        internal static string RenameToOriginalToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("RenameToOriginalToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        internal static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All Settings.
        /// </summary>
        internal static string ResetAllSettingsToolStripMenuItem {
            get {
                return ResourceManager.GetString("ResetAllSettingsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt RSA Key (*.serk)|*.serk.
        /// </summary>
        internal static string RSAKeyFilter {
            get {
                return ResourceManager.GetString("RSAKeyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSAPrivKey.serk.
        /// </summary>
        internal static string RSAPrivKeyFile {
            get {
                return ResourceManager.GetString("RSAPrivKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSAPubKey.serk.
        /// </summary>
        internal static string RSAPubKeyFile {
            get {
                return ResourceManager.GetString("RSAPubKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Key File.
        /// </summary>
        internal static string SaveKeyFile {
            get {
                return ResourceManager.GetString("SaveKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured.
        /// </summary>
        internal static string Secured {
            get {
                return ResourceManager.GetString("Secured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Delete File.
        /// </summary>
        internal static string SecureDeleteFile {
            get {
                return ResourceManager.GetString("SecureDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Delete Folder.
        /// </summary>
        internal static string SecureDeleteFolder {
            get {
                return ResourceManager.GetString("SecureDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Delete.
        /// </summary>
        internal static string SecureDeleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("SecureDeleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured Files.
        /// </summary>
        internal static string SecuredFiles {
            get {
                return ResourceManager.GetString("SecuredFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilesList.BIN.
        /// </summary>
        internal static string SecuredFilesListFileName {
            get {
                return ResourceManager.GetString("SecuredFilesListFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured Folders.
        /// </summary>
        internal static string SecuredFolders {
            get {
                return ResourceManager.GetString("SecuredFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FoldersList.BIN.
        /// </summary>
        internal static string SecuredFoldersListFileName {
            get {
                return ResourceManager.GetString("SecuredFoldersListFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured Folders.
        /// </summary>
        internal static string SecuredFoldersToolStripMenuItem {
            get {
                return ResourceManager.GetString("SecuredFoldersToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure File.
        /// </summary>
        internal static string SecureFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("SecureFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure.
        /// </summary>
        internal static string SecureToolStripMenuItem {
            get {
                return ResourceManager.GetString("SecureToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Key File.
        /// </summary>
        internal static string SelectKeyFile {
            get {
                return ResourceManager.GetString("SelectKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Reference File.
        /// </summary>
        internal static string SelectReferenceFile {
            get {
                return ResourceManager.GetString("SelectReferenceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a secured file to open..
        /// </summary>
        internal static string SelectSecuredFile {
            get {
                return ResourceManager.GetString("SelectSecuredFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Inactivity Timeout.
        /// </summary>
        internal static string SetInactivityTimeoutStripMenuItem {
            get {
                return ResourceManager.GetString("SetInactivityTimeoutStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sesk.
        /// </summary>
        internal static string ShareableKeyExtension {
            get {
                return ResourceManager.GetString("ShareableKeyExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt Shareable Key (*.sesk)|*.sesk.
        /// </summary>
        internal static string ShareableKeyFilter {
            get {
                return ResourceManager.GetString("ShareableKeyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Keys.
        /// </summary>
        internal static string ShareKeysToolStripMenuItem {
            get {
                return ResourceManager.GetString("ShareKeysToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt OTP Encrypted File (*.seotpf)|*.seotpf.
        /// </summary>
        internal static string SharpEncryptOTPEncryptedFile {
            get {
                return ResourceManager.GetString("SharpEncryptOTPEncryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .seotpf.
        /// </summary>
        internal static string SharpEncryptOTPEncryptedFileExtension {
            get {
                return ResourceManager.GetString("SharpEncryptOTPEncryptedFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt OTP Key (*.seotpk)|*.seotpk.
        /// </summary>
        internal static string SharpEncryptOTPKeyFilter {
            get {
                return ResourceManager.GetString("SharpEncryptOTPKeyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt Password Store File (*.seotppf)|*.seotppf.
        /// </summary>
        internal static string SharpEncryptPasswordStoreFile {
            get {
                return ResourceManager.GetString("SharpEncryptPasswordStoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt Password Store File Key (*.seotppfk)|*.seotppfk.
        /// </summary>
        internal static string SharpEncryptPasswordStoreFileKey {
            get {
                return ResourceManager.GetString("SharpEncryptPasswordStoreFileKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncryptSettings.BIN.
        /// </summary>
        internal static string SharpEncryptSettingsFileName {
            get {
                return ResourceManager.GetString("SharpEncryptSettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Excluded Secured Files.
        /// </summary>
        internal static string ShowAllSecuredFiles {
            get {
                return ResourceManager.GetString("ShowAllSecuredFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Excluded Secured Folders.
        /// </summary>
        internal static string ShowAllSecuredFolders {
            get {
                return ResourceManager.GetString("ShowAllSecuredFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Help.
        /// </summary>
        internal static string ShowHelpToolStripMenuItem {
            get {
                return ResourceManager.GetString("ShowHelpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show In Folder Tool Strip Menu Item.
        /// </summary>
        internal static string ShowInFolderToolStripMenuItem {
            get {
                return ResourceManager.GetString("ShowInFolderToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string ShowToolStripMenuItem {
            get {
                return ResourceManager.GetString("ShowToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Securing And Remove From List.
        /// </summary>
        internal static string StopSecuringAndRemoveFromListToolStripMenuItem {
            get {
                return ResourceManager.GetString("StopSecuringAndRemoveFromListToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Securing.
        /// </summary>
        internal static string StopSecuringToolStripMenuItem {
            get {
                return ResourceManager.GetString("StopSecuringToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Type.
        /// </summary>
        internal static string StoreType {
            get {
                return ResourceManager.GetString("StoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task completed successfully..
        /// </summary>
        internal static string TaskCompletedSuccessfully {
            get {
                return ResourceManager.GetString("TaskCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Count.
        /// </summary>
        internal static string TaskCountToolStripMenuItem {
            get {
                return ResourceManager.GetString("TaskCountToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Progress.
        /// </summary>
        internal static string TaskProgressForm {
            get {
                return ResourceManager.GetString("TaskProgressForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tasks remaining..
        /// </summary>
        internal static string TasksRemaining {
            get {
                return ResourceManager.GetString("TasksRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Type.
        /// </summary>
        internal static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Input.
        /// </summary>
        internal static string TextInput {
            get {
                return ResourceManager.GetString("TextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Viewer.
        /// </summary>
        internal static string TextViewer {
            get {
                return ResourceManager.GetString("TextViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files were not re-encrypted: {0}.
        /// </summary>
        internal static string TheFollowingWereNotReEncrypted {
            get {
                return ResourceManager.GetString("TheFollowingWereNotReEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are active tasks, to exit please use &apos;Force Exit&apos;. Active tasks can be viewed by selecting &apos;Active Tasks&apos; in the Debug menu..
        /// </summary>
        internal static string ThereAreActiveTasks {
            get {
                return ResourceManager.GetString("ThereAreActiveTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Size (GB).
        /// </summary>
        internal static string TotalSize {
            get {
                return ResourceManager.GetString("TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UncontainerizedFiles.BIN.
        /// </summary>
        internal static string UncontainerizedFilesLogFileName {
            get {
                return ResourceManager.GetString("UncontainerizedFilesLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use A Different Password For Each File.
        /// </summary>
        internal static string UseADifferentPasswordForEachFile {
            get {
                return ResourceManager.GetString("UseADifferentPasswordForEachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Keys.
        /// </summary>
        internal static string UserKeys {
            get {
                return ResourceManager.GetString("UserKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No private key currently exists, please generate another..
        /// </summary>
        internal static string UserPrivateKeyDoesNotExist {
            get {
                return ResourceManager.GetString("UserPrivateKeyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use session password.
        /// </summary>
        internal static string UseSessionPassword {
            get {
                return ResourceManager.GetString("UseSessionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Container.
        /// </summary>
        internal static string ValidateContainerToolStripMenuItem {
            get {
                return ResourceManager.GetString("ValidateContainerToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a valid container..
        /// </summary>
        internal static string ValidContainer {
            get {
                return ResourceManager.GetString("ValidContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Completed Tasks.
        /// </summary>
        internal static string ViewCompletedTasksToolStripMenuItem {
            get {
                return ResourceManager.GetString("ViewCompletedTasksToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log.
        /// </summary>
        internal static string ViewLogToolStripMenuItem {
            get {
                return ResourceManager.GetString("ViewLogToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Tasks.
        /// </summary>
        internal static string ViewTasks {
            get {
                return ResourceManager.GetString("ViewTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Tasks.
        /// </summary>
        internal static string ViewTasksToolStripMenuItem {
            get {
                return ResourceManager.GetString("ViewTasksToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for drive {0}.
        /// </summary>
        internal static string WaitingForDrive {
            get {
                return ResourceManager.GetString("WaitingForDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Free Disk Space After A Secure Delete.
        /// </summary>
        internal static string WipeDiskSpaceAfterSecureDeleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("WipeDiskSpaceAfterSecureDeleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Free Disk Space.
        /// </summary>
        internal static string WipeFreeDiskSpaceToolStripMenuItem {
            get {
                return ResourceManager.GetString("WipeFreeDiskSpaceToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Free Space After Secure Delete.
        /// </summary>
        internal static string WipeFreeSpaceAfterSecureDelete {
            get {
                return ResourceManager.GetString("WipeFreeSpaceAfterSecureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Rounds.
        /// </summary>
        internal static string WipeNumber {
            get {
                return ResourceManager.GetString("WipeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Options.
        /// </summary>
        internal static string WipeOptions {
            get {
                return ResourceManager.GetString("WipeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Rounds.
        /// </summary>
        internal static string WipeRounds {
            get {
                return ResourceManager.GetString("WipeRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Type.
        /// </summary>
        internal static string WipeType {
            get {
                return ResourceManager.GetString("WipeType", resourceCulture);
            }
        }
    }
}
