//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpEncrypt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpEncrypt.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("AboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error has occurred..
        /// </summary>
        internal static string ACriticalErrorHasOccurred {
            get {
                return ResourceManager.GetString("ACriticalErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} jobs..
        /// </summary>
        internal static string AddedNJobs {
            get {
                return ResourceManager.GetString("AddedNJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job.
        /// </summary>
        internal static string AddJob {
            get {
                return ResourceManager.GetString("AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a file to be secured..
        /// </summary>
        internal static string AddSecuredFile {
            get {
                return ResourceManager.GetString("AddSecuredFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Secured Folder.
        /// </summary>
        internal static string AddSecuredFolderToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("AddSecuredFolderToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string AdvancedToolStripMenuItem {
            get {
                return ResourceManager.GetString("AdvancedToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        internal static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous Rename.
        /// </summary>
        internal static string AnonymousRenameToolStripMenuItem {
            get {
                return ResourceManager.GetString("AnonymousRenameToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure_ {
            get {
                return ResourceManager.GetString("AreYouSure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Space (GB).
        /// </summary>
        internal static string AvailableSize {
            get {
                return ResourceManager.GetString("AvailableSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Jobs.
        /// </summary>
        internal static string ClearJobs {
            get {
                return ResourceManager.GetString("ClearJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select encrypted files to share keys with others..
        /// </summary>
        internal static string ClickToShare {
            get {
                return ResourceManager.GetString("ClickToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Oliver Bathurst 2020.
        /// </summary>
        internal static string CreatedByCredits {
            get {
                return ResourceManager.GetString("CreatedByCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string DebugMenuStrip {
            get {
                return ResourceManager.GetString("DebugMenuStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string DebugToolStripMenuItem {
            get {
                return ResourceManager.GetString("DebugToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt File.
        /// </summary>
        internal static string DecryptFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("DecryptFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt permanently.
        /// </summary>
        internal static string DecryptPermanentlyToolStripMenuItem {
            get {
                return ResourceManager.GetString("DecryptPermanentlyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt temporarily.
        /// </summary>
        internal static string DecryptTemporarilyToolStripMenuItem {
            get {
                return ResourceManager.GetString("DecryptTemporarilyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog.
        /// </summary>
        internal static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Tools.
        /// </summary>
        internal static string DiskToolsToolStripMenuItem {
            get {
                return ResourceManager.GetString("DiskToolsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        internal static string DoesNotExist {
            get {
                return ResourceManager.GetString("DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        internal static string Drive {
            get {
                return ResourceManager.GetString("Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Format.
        /// </summary>
        internal static string DriveFormat {
            get {
                return ResourceManager.GetString("DriveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Type.
        /// </summary>
        internal static string DriveType {
            get {
                return ResourceManager.GetString("DriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate identity found, please use another..
        /// </summary>
        internal static string DuplicateIdentity {
            get {
                return ResourceManager.GetString("DuplicateIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt Encrypted File (*.seef)|*.seef.
        /// </summary>
        internal static string EncryptedFileFilter {
            get {
                return ResourceManager.GetString("EncryptedFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitToolStripMenuItem {
            get {
                return ResourceManager.GetString("ExitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; cannot be empty..
        /// </summary>
        internal static string FieldCannotBeEmpty {
            get {
                return ResourceManager.GetString("FieldCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenuStripItem {
            get {
                return ResourceManager.GetString("FileMenuStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Key For File.
        /// </summary>
        internal static string GenerateKeyForFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("GenerateKeyForFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate New Key Pair.
        /// </summary>
        internal static string GenerateNewKeyPairToolStripMenuItem {
            get {
                return ResourceManager.GetString("GenerateNewKeyPairToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        internal static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to password management..
        /// </summary>
        internal static string GoToPasswordManagement {
            get {
                return ResourceManager.GetString("GoToPasswordManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Wipe Dialog.
        /// </summary>
        internal static string HDDWipeDialog {
            get {
                return ResourceManager.GetString("HDDWipeDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenuStrip {
            get {
                return ResourceManager.GetString("HelpMenuStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported Keys.
        /// </summary>
        internal static string ImportedKeysDir {
            get {
                return ResourceManager.GetString("ImportedKeysDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Public Key.
        /// </summary>
        internal static string ImportPublicKeyDialogTitle {
            get {
                return ResourceManager.GetString("ImportPublicKeyDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subfolders.
        /// </summary>
        internal static string IncludeSubfolders {
            get {
                return ResourceManager.GetString("IncludeSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key, please generate a new key-pair..
        /// </summary>
        internal static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating a new key pair will overwrite any existing keys, continue?.
        /// </summary>
        internal static string KeyPairDisclaimer {
            get {
                return ResourceManager.GetString("KeyPairDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.txt.
        /// </summary>
        internal static string LogFileName {
            get {
                return ResourceManager.GetString("LogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string LoggingDir {
            get {
                return ResourceManager.GetString("LoggingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string LoggingToolStripMenuItem {
            get {
                return ResourceManager.GetString("LoggingToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Obfuscation Rounds.
        /// </summary>
        internal static string NameObfuscationRounds {
            get {
                return ResourceManager.GetString("NameObfuscationRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never show again.
        /// </summary>
        internal static string NeverShowAgain {
            get {
                return ResourceManager.GetString("NeverShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drives selected..
        /// </summary>
        internal static string NoDrivesSelected {
            get {
                return ResourceManager.GetString("NoDrivesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid container..
        /// </summary>
        internal static string NotAValidContainer {
            get {
                return ResourceManager.GetString("NotAValidContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Pad.
        /// </summary>
        internal static string OneTimePadToolStripMenuItem {
            get {
                return ResourceManager.GetString("OneTimePadToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open a file from the default secure folder..
        /// </summary>
        internal static string OpenHomeFolder {
            get {
                return ResourceManager.GetString("OpenHomeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Secured.
        /// </summary>
        internal static string OpenSecuredToolStripMenuItem {
            get {
                return ResourceManager.GetString("OpenSecuredToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("OptionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The One Time Pad Vernam cipher requires that a key be generated that is either equal to or greater in length than that of the file to encrypt. e.g. a 2MB file will require at least a key of size 2MB. This cipher is widely regarded as perfect and unbreakable. It is therefore a necessity that the key is not stored with the encrypted file in a SharpEncrypt container, as the key would have to be encrypted with an inferior cipher. The next dialog will ask you for a location to store the key file. It is best to s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OTPDisclaimer {
            get {
                return ResourceManager.GetString("OTPDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Input Dialog.
        /// </summary>
        internal static string PasswordInputDialogTitle {
            get {
                return ResourceManager.GetString("PasswordInputDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided password is empty..
        /// </summary>
        internal static string PasswordIsEmpty {
            get {
                return ResourceManager.GetString("PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must not contain any restricted characters: {0}.
        /// </summary>
        internal static string PasswordRestrictedChars {
            get {
                return ResourceManager.GetString("PasswordRestrictedChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Obfuscation Rounds.
        /// </summary>
        internal static string PropertyObfuscationRounds {
            get {
                return ResourceManager.GetString("PropertyObfuscationRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicKeys.BIN.
        /// </summary>
        internal static string PubKeysFile {
            get {
                return ResourceManager.GetString("PubKeysFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A public key does not exist for this user, please generate another..
        /// </summary>
        internal static string PublicKeyDoesNotExist {
            get {
                return ResourceManager.GetString("PublicKeyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        internal static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove file from list but keep secured.
        /// </summary>
        internal static string RemoveFileFromListButKeepSecuredToolStripMenuItem {
            get {
                return ResourceManager.GetString("RemoveFileFromListButKeepSecuredToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove folder from list but keep secured.
        /// </summary>
        internal static string RemoveFolderFromListToolStripMenuItem {
            get {
                return ResourceManager.GetString("RemoveFolderFromListToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename to original.
        /// </summary>
        internal static string RenameToOriginalToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("RenameToOriginalToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings.
        /// </summary>
        internal static string ResetAllSettingsToolStripMenuItem {
            get {
                return ResourceManager.GetString("ResetAllSettingsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt RSA Key (*.serk)|*.serk.
        /// </summary>
        internal static string RSAKeyFilter {
            get {
                return ResourceManager.GetString("RSAKeyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSAPrivKey.serk.
        /// </summary>
        internal static string RSAPrivKeyFile {
            get {
                return ResourceManager.GetString("RSAPrivKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSAPubKey.serk.
        /// </summary>
        internal static string RSAPubKeyFile {
            get {
                return ResourceManager.GetString("RSAPubKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Key File.
        /// </summary>
        internal static string SaveKeyFile {
            get {
                return ResourceManager.GetString("SaveKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured.
        /// </summary>
        internal static string Secured {
            get {
                return ResourceManager.GetString("Secured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Delete.
        /// </summary>
        internal static string SecureDeleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("SecureDeleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilesList.BIN.
        /// </summary>
        internal static string SecuredFilesListFileName {
            get {
                return ResourceManager.GetString("SecuredFilesListFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured Folders.
        /// </summary>
        internal static string SecuredFolders {
            get {
                return ResourceManager.GetString("SecuredFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FoldersList.BIN.
        /// </summary>
        internal static string SecuredFoldersListFileName {
            get {
                return ResourceManager.GetString("SecuredFoldersListFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured Folders.
        /// </summary>
        internal static string SecuredFoldersToolStripMenuItem {
            get {
                return ResourceManager.GetString("SecuredFoldersToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure File.
        /// </summary>
        internal static string SecureFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("SecureFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure.
        /// </summary>
        internal static string SecureToolStripMenuItem {
            get {
                return ResourceManager.GetString("SecureToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Key File.
        /// </summary>
        internal static string SelectKeyFile {
            get {
                return ResourceManager.GetString("SelectKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Reference File.
        /// </summary>
        internal static string SelectReferenceFile {
            get {
                return ResourceManager.GetString("SelectReferenceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a secured file to open..
        /// </summary>
        internal static string SelectSecuredFile {
            get {
                return ResourceManager.GetString("SelectSecuredFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share keys.
        /// </summary>
        internal static string ShareKeysToolStripMenuItem {
            get {
                return ResourceManager.GetString("ShareKeysToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt OTP Encrypted File (*.seotpf)|*seotpf.
        /// </summary>
        internal static string SharpEncryptOTPEncryptedFile {
            get {
                return ResourceManager.GetString("SharpEncryptOTPEncryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncrypt OTP Key (*.seotpk)|*.seotpk.
        /// </summary>
        internal static string SharpEncryptOTPKeyFilter {
            get {
                return ResourceManager.GetString("SharpEncryptOTPKeyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpEncryptSettings.BIN.
        /// </summary>
        internal static string SharpEncryptSettingsFileName {
            get {
                return ResourceManager.GetString("SharpEncryptSettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Help.
        /// </summary>
        internal static string ShowHelpToolStripMenuItem {
            get {
                return ResourceManager.GetString("ShowHelpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Securing.
        /// </summary>
        internal static string StopSecuringToolStripMenuItem {
            get {
                return ResourceManager.GetString("StopSecuringToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Progress.
        /// </summary>
        internal static string TaskProgressForm {
            get {
                return ResourceManager.GetString("TaskProgressForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tasks remaining..
        /// </summary>
        internal static string TasksRemaining {
            get {
                return ResourceManager.GetString("TasksRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Type.
        /// </summary>
        internal static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Size (GB).
        /// </summary>
        internal static string TotalSize {
            get {
                return ResourceManager.GetString("TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Keys.
        /// </summary>
        internal static string UserKeys {
            get {
                return ResourceManager.GetString("UserKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use session password.
        /// </summary>
        internal static string UseSessionPassword {
            get {
                return ResourceManager.GetString("UseSessionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Container.
        /// </summary>
        internal static string ValidateContainerToolStripMenuItem {
            get {
                return ResourceManager.GetString("ValidateContainerToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a valid container..
        /// </summary>
        internal static string ValidContainer {
            get {
                return ResourceManager.GetString("ValidContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Completed Jobs.
        /// </summary>
        internal static string ViewCompletedJobsToolStripMenuItem {
            get {
                return ResourceManager.GetString("ViewCompletedJobsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Jobs.
        /// </summary>
        internal static string ViewJobs {
            get {
                return ResourceManager.GetString("ViewJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Jobs.
        /// </summary>
        internal static string ViewJobsToolStripMenuItem {
            get {
                return ResourceManager.GetString("ViewJobsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe free disk space after secure delete.
        /// </summary>
        internal static string WipeDiskSpaceAfterSecureDeleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("WipeDiskSpaceAfterSecureDeleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Free Disk Space.
        /// </summary>
        internal static string WipeFreeDiskSpaceToolStripMenuItem {
            get {
                return ResourceManager.GetString("WipeFreeDiskSpaceToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Rounds.
        /// </summary>
        internal static string WipeNumber {
            get {
                return ResourceManager.GetString("WipeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Options.
        /// </summary>
        internal static string WipeOptions {
            get {
                return ResourceManager.GetString("WipeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Rounds.
        /// </summary>
        internal static string WipeRounds {
            get {
                return ResourceManager.GetString("WipeRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Type.
        /// </summary>
        internal static string WipeType {
            get {
                return ResourceManager.GetString("WipeType", resourceCulture);
            }
        }
    }
}
